version: "3"
services:
  db:
    image: postgres
    ports: 
      - "5433:5432"
    # volumes:
      # - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: airbnb_clone
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  redis:
    image: redis
    ports:
      - "6379"
  api:
    build: .
    working_dir: /airbnb/packages/server
    # command: yarn start
    command: bash -c "yarn && ./node_modules/.bin/nodemon --watch ./src --exec ./node_modules/.bin/ts-node src/index.ts"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: airbnb_clone
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      NODE_ENV: develop
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    volumes:
      - ./files:/airbnb/files
      - .:/airbnb
    links: 
      - db
  # web:
  #   build: .
  #   working_dir: /airbnb/packages/web
  #   command: bash -c "cd src && ls -la && cd .. && yarn && yarn start"
  #   volumes:
  #     - ./src:/airbnb/packages/web/src
  #     - ./package.json:/airbnb/packages/web/src/package.json
  #   ports: 
  #     - "3000:3000"
