version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tomas
      POSTGRES_PASSWORD: test
      POSTGRES_DB: airbnb-clone
  api:
    build: ./packages/server
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      NODE_ENV: develop
    depends_on:
      - db
      - redis
    command: ./node_modules/.bin/nodemon -e ts -w ./src -x ./node_modules/.bin/ts-node src/index.ts
    volumes:
      - ./files:/app/files